### ISSUE TITLE
Tn-seq_Explorer.jar

### ISSUE THREAD

**Issue by willfurnass** [sina-cb/Tn-seqExplorer#1]
The documentation asks the user to run this `.jar` file; how does the user compile it?

**Comment by sina-cb** [comment]
You can import the project into Eclipse IDE to compile the code. Alternatively, you can get a pre-compiled version of the jar file from this link: http://www.cmbl.uga.edu/downloads/programs/Tn_seq_Explorer/

**Comment by willfurnass** [comment]
Thanks. It would be useful to add this information to a `README.md` file in this repository.
